### ISSUE TITLE
Bug with 4+ digits numbers

### ISSUE THREAD

**Issue by ImRaddar** [bowser0000/SkyblockMod#1]
![download - 2020-08-02T165403 894](https://user-images.githubusercontent.com/51541989/89126817-29160980-d4e9-11ea-8a83-4ab6caac62ea.png)
can you add a comma for 4 digits+ numbers so they don't look like this? thanks in advance

**Comment by bowser0000** [comment]
Fixed in commit [4655b12](https://github.com/bowser0000/SkyblockMod/commit/4655b12ae7cf1735bc951343fe2bc9679d7cb529)
