### ISSUE TITLE
Crash when entering side quests

### ISSUE THREAD

**Issue by Ibomber12** [bowser0000/SkyblockMod#105]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLLoadingPlugin (ModCore_Container-1.0.jar)
  CTJSLoadingPlugin (ctjs-1.2.2-1.8.9.jar)
  OptifinePatcherTweaker (Patcher-1.2 (1.8.9).jar)
  FMLLoadingPlugin (OofMod-2.0.2 (1.8.9).jar)
  Perspective Mod ([1.8.9] Perspective Mod-3.0.jar)
  PatcherTweaker (Patcher-1.2 (1.8.9).jar)
  FMLLoadingPlugin (Scrollable Tooltips-1.2 (1.8.9).jar)
  FMLLoadingPlugin (AutoGG-3.4 (1.8.9).jar)
  LabyModCoreMod (LabyMod-3.jar)
  SkyblockAddonsLoadingPlugin (SkyblockAddons-1.5.2-for-MC-1.8.9.jar)
  Main (OldAnimationsMod v2.4.2 FORGE MC1.8.9.jar)
  PlayerAPIPlugin (PlayerAPI-1.8.9-1.0.jar)
  FMLLoadingPlugin (Skypixel-0.0.6.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 6/11/21 1:21 PM
Description: Updating screen events

java.lang.NoSuchMethodError: net.minecraft.client.gui.inventory.GuiChest.getSlotUnderMouse()Lnet/minecraft/inventory/Slot;
	at me.Danker.DankersSkyblockMod.onGuiMouseInputPre(DankersSkyblockMod.java:2893)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_70_DankersSkyblockMod_onGuiMouseInputPre_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at me.Danker.DankersSkyblockMod.onGuiMouseInputPre(DankersSkyblockMod.java:2893)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_70_DankersSkyblockMod_onGuiMouseInputPre_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)

-- Affected screen --
Details:
	Screen name: net.labymod.mojang.inventory.GuiChestCustom

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['Ibomber'/500856, l='MpServer', x=-1.92, y=94.00, z=30.87], EntityOtherPlayerMP['NotADrake'/500857, l='MpServer', x=-1.94, y=105.24, z=30.84]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 0.00,100.00,0.00 - World: (0,100,0), Chunk: (at 0,6,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 239 game time, 2329 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 82 total; [EntityArmorStand['Armor Stand'/500791, l='MpServer', x=6.50, y=104.44, z=31.50], EntityPlayerSP['Ibomber'/500856, l='MpServer', x=-1.92, y=94.00, z=30.87], EntityVillager['Villager'/500786, l='MpServer', x=8.50, y=94.00, z=33.50], EntityArmorStand['Armor Stand'/500799, l='MpServer', x=9.50, y=90.00, z=22.50], EntityArmorStand['Armor Stand'/500798, l='MpServer', x=-2.50, y=90.00, z=22.50], EntityArmorStand['Armor Stand'/500797, l='MpServer', x=9.50, y=90.00, z=40.50], EntityArmorStand['Armor Stand'/500796, l='MpServer', x=15.50, y=90.00, z=40.50], EntityArmorStand['Armor Stand'/500795, l='MpServer', x=3.50, y=90.00, z=34.50], EntityArmorStand['Armor Stand'/500794, l='MpServer', x=3.50, y=90.00, z=40.50], EntityArmorStand['Armor Stand'/500793, l='MpServer', x=6.50, y=91.65, z=31.50], EntityArmorStand['Armor Stand'/500792, l='MpServer', x=3.50, y=90.00, z=28.50], EntityArmorStand['Armor Stand'/500807, l='MpServer', x=3.50, y=90.00, z=22.50], EntityArmorStand['§f? §cNo Destination'/500935, l='MpServer', x=12.50, y=93.44, z=25.50], EntityArmorStand['Armor Stand'/500806, l='MpServer', x=15.50, y=90.00, z=28.50], EntityArmorStand['Armor Stand'/500805, l='MpServer', x=9.50, y=90.00, z=28.50], EntityArmorStand['Armor Stand'/500804, l='MpServer', x=-2.50, y=90.00, z=34.50], EntityArmorStand['Armor Stand'/500803, l='MpServer', x=15.50, y=90.00, z=22.50], EntityArmorStand['Armor Stand'/500802, l='MpServer', x=9.50, y=90.00, z=34.50], EntityArmorStand['Armor Stand'/500801, l='MpServer', x=-2.50, y=90.00, z=40.50], EntityArmorStand['Armor Stand'/500800, l='MpServer', x=-2.50, y=90.00, z=28.50], EntityArmorStand['Armor Stand'/500815, l='MpServer', x=-4.31, y=93.13, z=30.47], EntityArmorStand['§bTravel to:'/500943, l='MpServer', x=16.00, y=100.94, z=31.50], EntityArmorStand['Armor Stand'/500814, l='MpServer', x=-4.31, y=93.13, z=32.59], EntityArmorStand['§9? §aWarp To §aHub'/500942, l='MpServer', x=6.50, y=88.44, z=31.50], EntityArmorStand['Armor Stand'/500813, l='MpServer', x=-4.03, y=93.13, z=32.47], EntityArmorStand['§7? §aWarp To §8Hub'/500941, l='MpServer', x=6.50, y=99.44, z=31.50], EntityArmorStand['Armor Stand'/500812, l='MpServer', x=-4.00, y=93.13, z=30.56], EntityArmorStand['§5? §aWarp To §2Green'/500940, l='MpServer', x=14.50, y=93.44, z=25.50], EntityArmorStand['Armor Stand'/500811, l='MpServer', x=-3.91, y=93.13, z=32.13], EntityArmorStand['§e§lCLICK'/500939, l='MpServer', x=8.50, y=93.84, z=33.50], EntityArmorStand['Armor Stand'/500810, l='MpServer', x=-3.88, y=93.13, z=30.88], EntityArmorStand['Jerry'/500938, l='MpServer', x=8.50, y=94.09, z=33.50], EntityArmorStand['Armor Stand'/500809, l='MpServer', x=-3.88, y=93.13, z=31.53], EntityArmorStand['§6§lNEW UPDATE'/500937, l='MpServer', x=8.50, y=94.34, z=33.50], EntityArmorStand['Armor Stand'/500808, l='MpServer', x=15.50, y=90.00, z=34.50], EntityArmorStand['§b? §cNo Destination'/500936, l='MpServer', x=14.50, y=93.44, z=23.50], EntityArmorStand['Armor Stand'/500823, l='MpServer', x=-4.34, y=93.97, z=31.69], EntityArmorStand['§bTravel to:'/500951, l='MpServer', x=-3.00, y=100.94, z=31.50], EntityArmorStand['Armor Stand'/500822, l='MpServer', x=-4.34, y=93.97, z=30.78], EntityArmorStand['§8? §aWarp To §7Portals'/500950, l='MpServer', x=5.50, y=92.44, z=42.50], EntityArmorStand['Armor Stand'/500821, l='MpServer', x=-4.00, y=93.16, z=31.50], EntityArmorStand['§7Click HERE to remove'/500949, l='MpServer', x=6.50, y=100.19, z=22.00], EntityArmorStand['Armor Stand'/500820, l='MpServer', x=-4.59, y=93.16, z=31.84], EntityArmorStand['§aThe Farming Islands'/500948, l='MpServer', x=6.50, y=100.56, z=22.00], EntityArmorStand['Armor Stand'/500819, l='MpServer', x=-4.56, y=93.13, z=30.91], EntityArmorStand['§bTravel to:'/500947, l='MpServer', x=6.50, y=100.94, z=22.00], EntityArmorStand['Armor Stand'/500818, l='MpServer', x=-4.91, y=93.16, z=31.50], EntityArmorStand['§6? §aWarp To §dFarms'/500946, l='MpServer', x=7.50, y=92.44, z=42.50], EntityArmorStand['Armor Stand'/500817, l='MpServer', x=-5.28, y=94.31, z=30.38], EntityArmorStand['§7Click HERE to remove'/500945, l='MpServer', x=16.00, y=100.19, z=31.50], EntityArmorStand['Armor Stand'/500816, l='MpServer', x=-4.19, y=92.56, z=31.47], EntityArmorStand['§aSavanna Woodland'/500944, l='MpServer', x=16.00, y=100.56, z=31.50], EntityArmorStand['Armor Stand'/500831, l='MpServer', x=-4.44, y=93.03, z=30.03], EntityArmorStand['Armor Stand'/500959, l='MpServer', x=18.50, y=94.44, z=13.50], EntityArmorStand['Armor Stand'/500830, l='MpServer', x=-3.94, y=93.06, z=30.22], EntityArmorStand['§a? §aWarp To §9Minions'/500958, l='MpServer', x=17.50, y=92.44, z=32.50], EntityArmorStand['Armor Stand'/500829, l='MpServer', x=-4.13, y=93.44, z=30.44], EntityArmorStand['§2? §aWarp To §5Purple'/500957, l='MpServer', x=12.50, y=93.44, z=23.50], EntityArmorStand['Armor Stand'/500828, l='MpServer', x=-4.47, y=93.41, z=30.31], EntityArmorStand['§7Click HERE to remove'/500956, l='MpServer', x=6.50, y=100.19, z=41.00], EntityArmorStand['Armor Stand'/500827, l='MpServer', x=-4.38, y=93.44, z=32.69], EntityArmorStand['§aBlazing Fortress'/500955, l='MpServer', x=6.50, y=100.56, z=41.00], EntityArmorStand['Armor Stand'/500826, l='MpServer', x=-3.19, y=93.88, z=32.34], EntityArmorStand['§bTravel to:'/500954, l='MpServer', x=6.50, y=100.94, z=41.00], EntityArmorStand['Armor Stand'/500825, l='MpServer', x=-5.28, y=94.31, z=31.28], EntityArmorStand['§7Click HERE to remove'/500953, l='MpServer', x=-3.00, y=100.19, z=31.50], EntityArmorStand['Armor Stand'/500824, l='MpServer', x=-4.56, y=92.81, z=31.50], EntityArmorStand['§aThe End'/500952, l='MpServer', x=-3.00, y=100.56, z=31.50], EntityArmorStand['Armor Stand'/500839, l='MpServer', x=-4.75, y=93.91, z=32.53], EntityArmorStand['Armor Stand'/500838, l='MpServer', x=-4.47, y=94.03, z=30.53], EntityArmorStand['Armor Stand'/500837, l='MpServer', x=-4.59, y=94.06, z=29.94], EntityArmorStand['Armor Stand'/500836, l='MpServer', x=-4.75, y=94.06, z=30.38], EntityArmorStand['Armor Stand'/500835, l='MpServer', x=-3.16, y=93.88, z=30.31], EntityArmorStand['Armor Stand'/500834, l='MpServer', x=-4.34, y=93.06, z=33.03], EntityArmorStand['Armor Stand'/500833, l='MpServer', x=-3.75, y=93.03, z=32.84], EntityArmorStand['Armor Stand'/500832, l='MpServer', x=-4.06, y=93.34, z=32.56], EntityArmorStand['§c? §aWarp To §eStorage'/500960, l='MpServer', x=17.50, y=92.44, z=30.50], EntityArmorStand['Armor Stand'/500842, l='MpServer', x=-4.97, y=93.66, z=31.91], EntityArmorStand['Armor Stand'/500841, l='MpServer', x=-4.94, y=93.66, z=31.06], EntityArmorStand['Armor Stand'/500840, l='MpServer', x=-4.34, y=94.09, z=31.84], EntityOtherPlayerMP['NotADrake'/500857, l='MpServer', x=-1.94, y=105.24, z=30.84], EntityOtherPlayerMP['NotADrake'/500857, l='MpServer', x=-1.94, y=105.24, z=30.84]]
	Retry entities: 0 total; []
	Server brand: Hypixel BungeeCord (1.0.29) <- vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:417)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	ct.js modules: [Module{name=DeepEquals,folder=.\config\ChatTriggers\modules\DeepEquals,metadata=ModuleMetadata(name=DeepEquals, version=1.0.0, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Compare two different objects for deep equality, requires=null, ignored=null, isRequired=false)}, Module{name=DeepProxy,folder=.\config\ChatTriggers\modules\DeepProxy,metadata=ModuleMetadata(name=DeepProxy, version=2.0.0, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=Ecolsson, description=null, requires=null, ignored=null, isRequired=false)}, Module{name=DungeonUtilities,folder=.\config\ChatTriggers\modules\DungeonUtilities,metadata=ModuleMetadata(name=DungeonUtilities, version=0.8.0, entry=index.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=null, requires=[SettingsManager], ignored=null, isRequired=false)}, Module{name=Elementa,folder=.\config\ChatTriggers\modules\Elementa,metadata=ModuleMetadata(name=Elementa, version=1.4.3, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Gui Library, requires=null, ignored=null, isRequired=false)}, Module{name=PersistentData,folder=.\config\ChatTriggers\modules\PersistentData,metadata=ModuleMetadata(name=PersistentData, version=1.1.3, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Easily store data that persist between game and ct reloads, requires=[DeepProxy], ignored=null, isRequired=false)}, Module{name=PersistentVariables,folder=.\config\ChatTriggers\modules\PersistentVariables,metadata=ModuleMetadata(name=PersistantVariables, version=null, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Easily create variables that persist between ct reloads, requires=[DeepEquals], ignored=null, isRequired=false)}, Module{name=Promise,folder=.\config\ChatTriggers\modules\Promise,metadata=ModuleMetadata(name=Promise, version=1.0.0, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Promise polyfill for 1.0.0, requires=null, ignored=null, isRequired=false)}, Module{name=request,folder=.\config\ChatTriggers\modules\request,metadata=ModuleMetadata(name=request, version=2.0.0, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=Ecolsson, description=A nicer alternative to XMLHttpRequest with a promise-like API. See the README.md for a full api description, requires=[Promise], ignored=null, isRequired=false)}, Module{name=SBInvSee,folder=.\config\ChatTriggers\modules\SBInvSee,metadata=ModuleMetadata(name=SBInvSee, version=1.0.1, entry=index.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=See the inventory contents of a hypixel skyblock player, requires=[request, PersistentData], ignored=null, isRequired=false)}, Module{name=SettingsManager,folder=.\config\ChatTriggers\modules\SettingsManager,metadata=ModuleMetadata(name=SettingsManager, version=1.2.1, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Autogenerates a settings file and gui based on the object created and registers. Example usage can be found in UseExample.js, requires=null, ignored=null, isRequired=false)}, Module{name=SkyblockCommands,folder=.\config\ChatTriggers\modules\SkyblockCommands,metadata=ModuleMetadata(name=&5&k&l00&r&3 Sky&2Block &6Commands &r&5&k&l00&r&c&o by &r&4&oDolphin0xyz, version=&3&l&k0&r&6&l&o1&3&l&o.&6&l&o4&3&l&o.&6&l&o2&r&3&l&k0, entry=main.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=&a&l&k0&r&3 Adds keybinds for most skyblock commands and fast travel warps in the vanilla controls menu. &r&a&l&k0
&r&e&l&k0&r&2 If keys conflicts with other keys things may not work and things outside this moudule may break. &r&e&l&k0
&r&b&l&k0&r&d Contact me if you find bugs, need help, or have features to suggest. My discord name is Dolphin0xyz#7887 and you can also find me on the ChatTriggers discord server. &r&b&l&k0, requires=null, ignored=null, isRequired=false)}]
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	CPU: 12x AMD Ryzen 5 1600 Six-Core Processor 
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 694927912 bytes (662 MB) / 1476395008 bytes (1408 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_I7 35 mods loaded, 35 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	perspectivemod{3.0} [Perspective Mod 3.0] (minecraft.jar) 
	UCHIJA	oldanimations{2.4.2} [OldAnimationsMod] (minecraft.jar) 
	UCHIJA	PlayerAPI{1.0} [Player API] (minecraft.jar) 
	UCHIJA	autotip{3.0.1} [Autotip] (Autotip-3.0.1 [1.8-1.12.2].jar) 
	UCHIJA	nick_hider{5.3.1} [Nick Hider] (Nick Hider-5.3.1 (1.8.9).jar) 
	UCHIJA	modcore{0.1.47} [ModCore] (Sk1er Modcore-0.1.47 (1.8.9).jar) 
	UCHIJA	Danker's Skyblock Mod{1.8.4} [Danker's Skyblock Mod] (1.8.9.Danker.s.Skyblock.Mod.-.1.8.4.jar) 
	UCHIJA	pownspotionhud{1.0} [pownspotionhud] (1.8.9_Powns_PotionEffect_HUD_-_1.0.jar) 
	UCHIJA	blockoverlay{2.1} [BlockOverlay] ([1.8.9] BlockOverlay-v2.1.jar) 
	UCHIJA	canelexkeystrokes{1.0} [Canelex Keystrokes] ([1.8.9] canelex keystrokes.jar) 
	UCHIJA	Powns ArmorStatus HUD{1.0} [powns-armorhud] ([1.8.9] Powns ArmorStatus HUD - 1.1.jar) 
	UCHIJA	pownscoordshud{1.0} [Powns' Coords HUD] ([1.8.9] Powns Coords HUD - 1.0.jar) 
	UCHIJA	pownstogglesneak{3.0} [pownstogglesneak] ([1.8.9] Powns ToggleSneak - 3.0.jar) 
	UCHIJA	sidebarmod{2.0} [Sidebar Mod Revamp] ([1.8.9] Sidebar Mod Revamp.jar) 
	UCHIJA	alwayssharp{1.0} [AlwaysSharp] (alwayssharp-1.0.jar) 
	UCHIJA	autogg{3.4} [AutoGG] (AutoGG-3.4 (1.8.9).jar) 
	UCHIJA	AutoWho{1.0} [AutoWho] (AutoWho-1.0.jar) 
	UCHIJA	ct.js{1.2.2} [ChatTriggers] (ctjs-1.2.2-1.8.9.jar) 
	UCHIJA	DiscordRP{1.2.4} [DiscordRP] (DiscordRP-1.2.4.jar) 
	UCHIJA	labymod{3.8.39} [LabyMod] (LabyMod-3.jar) 
	UCHIJA	modcore_example_mod{1.0} [ModCore Container Mod] (ModCore_Container-1.0.jar) 
	UCHIJA	refractionoof{2.0.2} [OofMod] (OofMod-2.0.2 (1.8.9).jar) 
	UCHIJA	patcher{1.2} [Patcher] (Patcher-1.2 (1.8.9).jar) 
	UCHIJA	quickplay{2.0.3} [Quickplay] (Quickplay-1.8.9-2.0.3.jar) 
	UCHIJA	resourcepackmanager{1.0} [Resource Pack Manager] (Resource_Pack_Manager_1.1.jar) 
	UCHIJA	text_overflow_scroll{1.2} [Scrollable Tooltips] (Scrollable Tooltips-1.2 (1.8.9).jar) 
	UCHIJA	hypixel_auto_complete{1.0} [Hypixel Autocomplete Mod] (Sk1er Hypixel Autocomplete Mod-1.0.jar) 
	UCHIJA	skyblockaddons{1.5.2} [SkyBlock Addons] (SkyblockAddons-1.5.2-for-MC-1.8.9.jar) 
	UCHIJA	skypixel{0.0.6} [Skypixel] (Skypixel-0.0.6.jar) 
	UCHIJA	skywarsmod{1.0} [SkyWars Stats Mod] (SkyWars Stats Mod-v1.0.3.jar) 
	UCHIJA	timechanger{1.0} [TimeChanger] (TimeChanger-1.0 (1.8.9).jar) 
	UCHIJA	publictogglechat{2.1.0} [§6Hypixel §7-§a ToggleChat] (ToggleChat-2.1.0-SNAPSHOT.jar) 
	Loaded coremods (and transformers): 
FMLLoadingPlugin (ModCore_Container-1.0.jar)
  
CTJSLoadingPlugin (ctjs-1.2.2-1.8.9.jar)
  com.chattriggers.ctjs.launch.plugin.CTJSTransformer
OptifinePatcherTweaker (Patcher-1.2 (1.8.9).jar)
  club.sk1er.patcher.tweaker.optifine.OptifineClassTransformer
FMLLoadingPlugin (OofMod-2.0.2 (1.8.9).jar)
  
Perspective Mod ([1.8.9] Perspective Mod-3.0.jar)
  net.canelex.perspectivemod.asm.CameraTransformer
PatcherTweaker (Patcher-1.2 (1.8.9).jar)
  club.sk1er.mods.core.forge.ClassTransformer
  club.sk1er.patcher.tweaker.ClassTransformer
FMLLoadingPlugin (Scrollable Tooltips-1.2 (1.8.9).jar)
  club.sk1er.mods.overflowscroll.forge.ClassTransformer
FMLLoadingPlugin (AutoGG-3.4 (1.8.9).jar)
  club.sk1er.mods.core.forge.ClassTransformer
LabyModCoreMod (LabyMod-3.jar)
  net.labymod.core.asm.LabyModTransformer
SkyblockAddonsLoadingPlugin (SkyblockAddons-1.5.2-for-MC-1.8.9.jar)
  codes.biscuit.skyblockaddons.tweaker.SkyblockAddonsTransformer
Main (OldAnimationsMod v2.4.2 FORGE MC1.8.9.jar)
  com.spiderfrog.main.ClassTransformer
PlayerAPIPlugin (PlayerAPI-1.8.9-1.0.jar)
  api.player.forge.PlayerAPITransformer
FMLLoadingPlugin (Skypixel-0.0.6.jar)
  io.prplz.skypixel.asm.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13596 Compatibility Profile Context 20.10.35.02 27.20.1034.6' Renderer: 'Radeon RX 580 Series'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: Radeon RX 580 Series GL version 4.6.13596 Compatibility Profile Context 20.10.35.02 27.20.1034.6, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: ThirtyVirus Pack V2.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 1600 Six-Core Processor

**Comment by bowser0000** [comment]
Update or use Sk1er's Old Animations
