### ISSUE TITLE
Experimentation Table Solvers not working

### ISSUE THREAD

**Issue by DestroOriginal** [bowser0000/SkyblockMod#108]
Mod List:
Dankers skyblock mod
skyblock addons
optifine
keystrokes

The only one working is chronomatron, but its only half
it shows the pattern at the side but it doesnt highlight the next or current one
For the ultra sequencer it doesnt do anything at all, same for superpairs

**Comment by CuzImClicks** [comment]
Are you using the newest version from the discord?
