### ISSUE TITLE
Gemstones in Lore option causing crash

### ISSUE THREAD

**Issue by MaterousApps** [bowser0000/SkyblockMod#126]
When the Show Applied Gemstones in Lore option is turned on, the recent changes to flawless gemstones have caused issues after applying the new gemstones into items.  It causes a java crash.  Previously applied gemstones don't cause issues, it appears to only happen on newly inserted gemstones.

*edit* Forgot to mention it only happens when hovering over the item after inserting.

**Comment by bowser0000** [comment]
Fixed in 12a69e0
