### ISSUE TITLE
Experimentation Solver not working

### ISSUE THREAD

**Issue by GungeonRider** [bowser0000/SkyblockMod#135]
After fixing the crashing conflict with OldAnimations, I tried the minigames and none of the three games had the solvers active, yet in the /dsm menu they are all set to ON. Here is my mod list:

![image](https://user-images.githubusercontent.com/124768953/217468107-22744d76-2fef-4699-b8f6-20c57e17dc58.png)
![image](https://user-images.githubusercontent.com/124768953/217468258-819e0b2d-828c-4938-a194-415039c63f3d.png)

**Comment by bowser0000** [comment]
spiderfrog's Old Animations breaks colouring slots, use Sk1er's Old Animations.

**Comment by GungeonRider** [comment]
I tried Sk1er's mod but it would make every player and enity invisible, so I went back to spiderfrog. Do you happen to know why enities would be invisible?
