### ISSUE TITLE
Ability to reset fishing loot if you've already imported existing stats or want to see stats on a fishing session by session

### ISSUE THREAD

**Issue by 1vsi** [bowser0000/SkyblockMod#2]
Could you add a command to reset the fishing loot statistics if you have already imported your existing fishing stats or want to reset the loot statistics after a fishing session?

**Comment by ImRaddar** [comment]
yeah hopefully he adds this to every tracker so we can have another session

**Comment by bowser0000** [comment]
Added in commits [92b0a79](https://github.com/bowser0000/SkyblockMod/commit/92b0a7959090b56ab313f77143ffd07a1483ea71) and [cd9303b](https://github.com/bowser0000/SkyblockMod/commit/cd9303b0c510005f6162468beb26eb4ec397a757).
