### ISSUE TITLE
Dungeons Crashing

### ISSUE THREAD

**Issue by Reaper245** [bowser0000/SkyblockMod#21]
I've crashed 4 times in dungeons and I thought it was NEU, but when I sent them the log, it turned out to be a danker crash. 
![image](https://user-images.githubusercontent.com/70851754/96476917-7dcd4480-11fb-11eb-8863-647d15bb4a72.png)

**Comment by bowser0000** [comment]
Will release new version soon, if you don't want to wait you can join [the discord](https://discord.gg/QsEkNQS) and get the beta in #new-commits which fixes it.
