### ISSUE TITLE
AOTD ability still activates even with "Disable AOTD Ability" when blocking with the AOTD when looking at a block.

### ISSUE THREAD

**Issue by SkilledHasBadPC** [bowser0000/SkyblockMod#25]
title

**Comment by cooldma** [comment]
That happens to me too and with the disable livid dagger ability.

**Comment by bowser0000** [comment]
Fixed in commit [9ec9e1c](https://github.com/bowser0000/SkyblockMod/commit/9ec9e1cb376ab39471a3a9fe3888d52626b3ee3b)
