### ISSUE TITLE
Slayer loot tracker rework + suggestions

### ISSUE THREAD

**Issue by ImRaddar** [bowser0000/SkyblockMod#3]
hey bowser000
can you change the slayer tracker method to track stuff? It's kinda bad and not efficient since sometimes you won't get the items or other people drops count towards your tracker

Suggestions:
- PET display with current level + exp | exp for next level
- Dungeon gear quality
- Notifications like the special zealot notification when you get a rngesus drop from slayers

**Comment by 1vsi** [comment]
Oh yeah, adding dungeon gear quality into the mod would be extremely helpful for all the folks who rely on skylea to check or dont have skyblock extras (me)

**Comment by bowser0000** [comment]
> Oh yeah, adding dungeon gear quality into the mod would be extremely helpful for all the folks who rely on skylea to check or dont have skyblock extras (me)

The SBA beta already has this feature, so I won't be adding it to this one. You can get the beta build from the development branch on the SBA repo.

**Comment by ImRaddar** [comment]
> > Oh yeah, adding dungeon gear quality into the mod would be extremely helpful for all the folks who rely on skylea to check or dont have skyblock extras (me)
> 
> The SBA beta already has this feature, so I won't be adding it to this one. You can get the beta build from the development branch on the SBA repo.

It would make the mod better ;(
