### ISSUE TITLE
Pet xp 

### ISSUE THREAD

**Issue by Vukas1966** [bowser0000/SkyblockMod#31]
When will you add pet xp show its not that hard job to do you can even copy the scrypts and like over 50 people want that uptade. Please

**Comment by notbozho** [comment]
When "it's not that hard" then why don't you do it by yourself? This mod and its creator are so amazing and he updates it regularly...just wait a bit smh.

**Comment by bowser0000** [comment]
Pet XP has been added to the NEU 2.0 prerelease
