### ISSUE TITLE
 Experimentation Table Solver

### ISSUE THREAD

**Issue by notbozho** [bowser0000/SkyblockMod#35]
A addon that helps you do the new "puzzles?, games" and earn lots of enchanting xp :)

**Comment by bowser0000** [comment]
Added in commits [5b733d0](https://github.com/bowser0000/SkyblockMod/commit/5b733d004e77b791aeb754b355e9a35eba168f7d), [b294ee1](https://github.com/bowser0000/SkyblockMod/commit/b294ee1f83d85bc58bc9b9f97f94135d395ebf74) and [d056aa0](https://github.com/bowser0000/SkyblockMod/commit/d056aa0ec706820a94e36e2c4866c15a12b9af6e)
