### ISSUE TITLE
[Enhancement] Add predictions to experiments

### ISSUE THREAD

**Issue by Chawiiee** [bowser0000/SkyblockMod#45]
When doing experiment to gain enchanting experience, it would be nice if as well as having the green background color to tell us where to click at that moment, there would be a yellow (or other color) to predict the move after the green one. This would make playing these games more smooth as you could now know where the next one will be at, instead of having to see the green appear after clicking the current one. Hope this gets added! :)

**Comment by fmpreferences** [comment]
came here to suggest this. chattriggers module ExperimentationTable has this feature and makes ultrasequencer much faster

**Comment by My-Name-Is-Jeff** [comment]
Should be implemented in #43

**Comment by bowser0000** [comment]
Added in commit [978c058](https://github.com/bowser0000/SkyblockMod/commit/978c058d05aa25da9c5e5c0ab8a85a63ed3b1c58)
