### ISSUE TITLE
[Enhancement] Remove tooltips in Ultrasequencer experiment

### ISSUE THREAD

**Issue by fmpreferences** [bowser0000/SkyblockMod#47]
The tooltips for the panes in the ultrasequencer experiment take up a lot of space and often cover up the next square to click. The ChatTriggers module ExperimentationTable does not show the tooltips. I originally overlooked this but this may be the biggest factor when it comes to speed on the ultrasequencer.

Edit: I now realize that turning off advanced tooltips would probably make the tooltips smaller; however, I don't think you can turn off advanced tooltips inside a gui so I think this should be a toggleable option to turn off tooltips in Ultrasequencer

**Comment by My-Name-Is-Jeff** [comment]
Should be implemented in #43

**Comment by bowser0000** [comment]
Added in commit [978c058](https://github.com/bowser0000/SkyblockMod/commit/978c058d05aa25da9c5e5c0ab8a85a63ed3b1c58)
