### ISSUE TITLE
Question: What are the uses of ForgeHax in this mod?

### ISSUE THREAD

**Issue by JacksonChen666** [bowser0000/SkyblockMod#58]
I went to the bottom of the readme of this repository, and found there's a credit for ForgeHax. My question is, what are the uses of the ForgeHax mod, and can the uses potentially get me banned?

I could not find the discussions tab, so I could only submit an issue as a question.

**Comment by flame-cat** [comment]
ForgeHax's draw entity border feature is used in this mod to highlight the correct blaze in the blaze puzzle solver.

There is nothing that can potentially get you banned.

**Comment by JacksonChen666** [comment]
Ok, thank you for the answer.
