### ISSUE TITLE
[Experimentation Table Solver] Ultrasequencer solver blocks clicking all numbers above 1

### ISSUE THREAD

**Issue by SkilledHasBadPC** [bowser0000/SkyblockMod#59]
I do not have these mods:
Old Animations ≤2.6.4

**Comment by flame-cat** [comment]
If you are using the PackHQ texture back, delete both null_pane files in assets\minecraft\mcpatcher\cit\ui
If you still have any issues, please go to issues-and-support in the discord server - https://discord.gg/pjUcwVKc

**Comment by SkilledHasBadPC** [comment]
> If you are using the PackHQ texture back, delete both null_pane files in assets\minecraft\mcpatcher\cit\ui
> If you still have any issues, please go to issues-and-support in the discord server - https://discord.gg/pjUcwVKc

I am not using the PackHQ texture pack.

**Comment by SkilledHasBadPC** [comment]
Fixed visuals, turns out it was FoamFix anarchy doing something weird
