### ISSUE TITLE
it keeps saying issue 403

### ISSUE THREAD

**Issue by Andmaster83** [bowser0000/SkyblockMod#6]
Whenever I try to access the api based commands it says that and also the display wont show up on my screen for some reason

**Comment by bowser0000** [comment]
Set your key using /setkey [key] to fix error 403. If you don't have a key, create a new one by doing /api new on Hypixel.
For the display issue, are you using LabyMod?

**Comment by bowser0000** [comment]
Closed due to inactivity.
