### ISSUE TITLE
Updating to newer mc Version - Forge/Fabric

### ISSUE THREAD

**Issue by UltraBlackLinux** [bowser0000/SkyblockMod#63]
Hey, there,
Is there any chance, of this getting updated to a newer MC-Version? I tried to get gradle to not complain about some stuff, but I failed. Minecraft seems not to get added as library. Also updating to a newer gradle was a problem at first. I don't know, how to make a Forge mod, so I hope, that you might update it! (Maybe even Fabric?)

Thanks a lot!

**Comment by RabbitType99** [comment]
This mod will say on forge and 1.8.9 but you can join the Danker Skyblock Mod Discord to get the compiled version.

**Comment by TheLegendOfKitty** [comment]
1) 
![player versions](https://user-images.githubusercontent.com/61601745/105611956-7e7ef500-5d6d-11eb-99b3-c52b3c7d847c.png)
most people use 1.8 as their version, and this mod will most likely never support other versions for this reason
2) i have no idea what you're trying to say but if you tried to compile the mod for a newer version of forge you can bet your ass it wont work

**Comment by UltraBlackLinux** [comment]
Have you noticed, that 1.16 is still 27%?

**Comment by RabbitType99** [comment]
> Have you noticed, that 1.16 is still 27%?

Yeah because it is the newest version. And how to indoduce more features if the mod needs to be updated every 6month more a minecraft update

**Comment by UltraBlackLinux** [comment]
> > Have you noticed, that 1.16 is still 27%?
> 
> Yeah because it is the newest version. And how to indoduce more features if the mod needs to be updated every 6month more a minecraft update

Forge != Fabric, my guy.
Forge: Update = change many lines inside of gradle and forge
Fabric: It just works, who even needs updates.

**Comment by pixelpresident** [comment]
> > > Have you noticed, that 1.16 is still 27%?
> > 
> > 
> > Yeah because it is the newest version. And how to indoduce more features if the mod needs to be updated every 6month more a minecraft update
> 
> Forge != Fabric, my guy.
> Forge: Update = change many lines inside of gradle and forge
> Fabric: It just works, who even needs updates.

What do you mean it “just works”, you still have to deal with mojangs BS every 3 updates.

**Comment by TheLegendOfKitty** [comment]
> > > Have you noticed, that 1.16 is still 27%?
> 
> > 
> 
> > Yeah because it is the newest version. And how to indoduce more features if the mod needs to be updated every 6month more a minecraft update
> 
> 
> 
> Forge != Fabric, my guy.
> 
> Forge: Update = change many lines inside of gradle and forge
> 
> Fabric: It just works, who even needs updates.

So are we just not going to talk about how every single fabric worldgen mod was fucked over in 1.16.4?

**Comment by TheLegendOfKitty** [comment]
> > > > Have you noticed, that 1.16 is still 27%?
> 
> > > 
> 
> > > 
> 
> > > Yeah because it is the newest version. And how to indoduce more features if the mod needs to be updated every 6month more a minecraft update
> 
> > 
> 
> > Forge != Fabric, my guy.
> 
> > Forge: Update = change many lines inside of gradle and forge
> 
> > Fabric: It just works, who even needs updates.
> 
> 
> 
> What do you mean it “just works”, you still have to deal with mojangs BS every 3 updates. 

^^^

**Comment by TheLegendOfKitty** [comment]
> Have you noticed, that 1.16 is still 27%?

1.16 is 27% because Mojang pushes people to use newer versions. It's the default version and Mojang has some bullshit "warning" that says your account is at risk with older versions. Most kids with some crappy Mac or windows are going to use 1.16.

**Comment by TheLegendOfKitty** [comment]
> Hey, there,
> Is there any chance, of this getting updated to a newer MC-Version? I tried to get gradle to not complain about some stuff, but I failed. Minecraft seems not to get added as library. Also updating to a newer gradle was a problem at first. I don't know, how to make a Forge mod, so I hope, that you might update it! (Maybe even Fabric?)
> 
> Thanks a lot!



> > > Have you noticed, that 1.16 is still 27%?
> > 
> > 
> > Yeah because it is the newest version. And how to indoduce more features if the mod needs to be updated every 6month more a minecraft update
> 
> Forge != Fabric, my guy.
> Forge: Update = change many lines inside of gradle and forge
> Fabric: It just works, who even needs updates.

Just came back to this. It seems like you don't know how thinks around here work; if there was even a fabric version for 1.8 it would still raise many errors. If you are having trouble compiling the ORIGINAL, 1.8 latest version, I would first recommend using java 8.

**Comment by RabbitType99** [comment]
Why would you use fabric for 1.8.9 if all mods except a few are on Forge. Although Fabric is not compatible with forge. You can say whatever you want. The mod will not be updated for a single dude who wants to use fabric because he is bad. Omegalul

**Comment by UltraBlackLinux** [comment]
> > Hey, there,
> > Is there any chance, of this getting updated to a newer MC-Version? I tried to get gradle to not complain about some stuff, but I failed. Minecraft seems not to get added as library. Also updating to a newer gradle was a problem at first. I don't know, how to make a Forge mod, so I hope, that you might update it! (Maybe even Fabric?)
> > Thanks a lot!
> 
> > > > Have you noticed, that 1.16 is still 27%?
> > > 
> > > 
> > > Yeah because it is the newest version. And how to indoduce more features if the mod needs to be updated every 6month more a minecraft update
> > 
> > 
> > Forge != Fabric, my guy.
> > Forge: Update = change many lines inside of gradle and forge
> > Fabric: It just works, who even needs updates.
> 
> Just came back to this. It seems like you don't know how thinks around here work; if there was even a fabric version for 1.8 it would still raise many errors. If you are having trouble compiling the ORIGINAL, 1.8 latest version, I would first recommend using java 8.

Who says, that I am talking about a 1.8 version? Why are you trying to tell me, that just writing a 1.8 mod in fabric will cause errors? Is that really something new? There isn't even a 1.8 version of fabric, sigh.

**Comment by UltraBlackLinux** [comment]
> > > > Have you noticed, that 1.16 is still 27%?
> > > 
> > > 
> > > Yeah because it is the newest version. And how to indoduce more features if the mod needs to be updated every 6month more a minecraft update
> > 
> > 
> > Forge != Fabric, my guy.
> > Forge: Update = change many lines inside of gradle and forge
> > Fabric: It just works, who even needs updates.
> 
> What do you mean it “just works”, you still have to deal with mojangs BS every 3 updates.

It's a client side mod, that mostly does gui stuffs. Even if minecraft updates, fabric will not change so much, that it breaks. You don't even know, what you are talking about.

**Comment by UltraBlackLinux** [comment]
> Why would you use fabric for 1.8.9 if all mods except a few are on Forge. Although Fabric is not compatible with forge. You can say whatever you want. The mod will not be updated for a single dude who wants to use fabric because he is bad. Omegalul

Are you trying to insult me? What was your goal here. Better stop using your dad's pc, 5yo.

**Comment by TheLegendOfKitty** [comment]
> > > Hey, there,
> > > Is there any chance, of this getting updated to a newer MC-Version? I tried to get gradle to not complain about some stuff, but I failed. Minecraft seems not to get added as library. Also updating to a newer gradle was a problem at first. I don't know, how to make a Forge mod, so I hope, that you might update it! (Maybe even Fabric?)
> > > Thanks a lot!
> > 
> > 
> > > > > Have you noticed, that 1.16 is still 27%?
> > > > 
> > > > 
> > > > Yeah because it is the newest version. And how to indoduce more features if the mod needs to be updated every 6month more a minecraft update
> > > 
> > > 
> > > Forge != Fabric, my guy.
> > > Forge: Update = change many lines inside of gradle and forge
> > > Fabric: It just works, who even needs updates.
> > 
> > 
> > Just came back to this. It seems like you don't know how thinks around here work; if there was even a fabric version for 1.8 it would still raise many errors. If you are having trouble compiling the ORIGINAL, 1.8 latest version, I would first recommend using java 8.
> 
> Who says, that I am talking about a 1.8 version? Why are you trying to tell me, that just writing a 1.8 mod in fabric will cause errors? Is that really something new? There isn't even a 1.8 version of fabric, sigh.

I literally just said "**if there was even a fabric version for 1.8**" in what you quoted. Please learn to read. You imply in the post that fabric mods will run on new versions without change to code. This already makes me question your qualification to support one mod loader or another when you don't even know how they work. 

> Forge != Fabric, my guy.
> Forge: Update = change many lines inside of gradle and forge
> Fabric: It just works, who even needs updates.



> > > > > Have you noticed, that 1.16 is still 27%?
> > > > 
> > > > 
> > > > Yeah because it is the newest version. And how to indoduce more features if the mod needs to be updated every 6month more a minecraft update
> > > 
> > > 
> > > Forge != Fabric, my guy.
> > > Forge: Update = change many lines inside of gradle and forge
> > > Fabric: It just works, who even needs updates.
> > 
> > 
> > What do you mean it “just works”, you still have to deal with mojangs BS every 3 updates.
> 
> It's a client side mod, that mostly does gui stuffs. Even if minecraft updates, fabric will not change so much, that it breaks. You don't even know, what you are talking about.

This is not true, and "gui stuffs" is not what these mods do. You have many other features and with every feature, it's a higher chance of breaking each update. Also, I recommend sharpening your grammar skills (a simple google search will suffice)

**Comment by TheLegendOfKitty** [comment]
> > Why would you use fabric for 1.8.9 if all mods except a few are on Forge. Although Fabric is not compatible with forge. You can say whatever you want. The mod will not be updated for a single dude who wants to use fabric because he is bad. Omegalul
> 
> Are you trying to insult me? What was your goal here. Better stop using your dad's pc, 5yo.

He's trying to tell you how absurd it is to update a mod to the latest version for one person. Especially when the mod is ran by one person. For free. Think about what you're requesting for a moment. Also, I find it strange how you don't tell this person there isn't a fabric version for 1.8 but you tell me when I clearly state it was a hypothetical.

**Comment by UltraBlackLinux** [comment]
> > > Why would you use fabric for 1.8.9 if all mods except a few are on Forge. Although Fabric is not compatible with forge. You can say whatever you want. The mod will not be updated for a single dude who wants to use fabric because he is bad. Omegalul
> > 
> > 
> > Are you trying to insult me? What was your goal here. Better stop using your dad's pc, 5yo.
> 
> He's trying to tell you how absurd it is to update a mod to the latest version for one person. Especially when the mod is ran by one person. For free. Think about what you're requesting for a moment. Also, I find it strange how you don't tell this person there isn't a fabric version for 1.8 but you tell me when I clearly state it was a hypothetical.

I'd like to hear the developer itself. I just asked, hoping for a dev reply, but you guys came and thought you knew, what he'd say. Just stop and wait for the owner.

**Comment by TrashCan69420** [comment]
i love rewriting a large chunk of the mod just to support the 20 people that play on 1.16 fabric on skyblock

**Comment by RabbitType99** [comment]
> > > > Why would you use fabric for 1.8.9 if all mods except a few are on Forge. Although Fabric is not compatible with forge. You can say whatever you want. The mod will not be updated for a single dude who wants to use fabric because he is bad. Omegalul
> > > 
> > > 
> > > Are you trying to insult me? What was your goal here. Better stop using your dad's pc, 5yo.
> > 
> > He's trying to tell you how absurd it is to update a mod to the latest version for one person. Especially when the mod is ran by one person. For free. Think about what you're requesting for a moment. Also, I find it strange how you don't tell this person there isn't a fabric version for 1.8 but you tell me when I clearly state it was a hypothetical.
> 
> I'd like to hear the developer itself. I just asked, hoping for a dev reply, but you guys came and thought you knew, what he'd say. Just stop and wait for the owner.

https://discord.gg/VKGBymbnRM

**Comment by TheLegendOfKitty** [comment]
> > > > Why would you use fabric for 1.8.9 if all mods except a few are on Forge. Although Fabric is not compatible with forge. You can say whatever you want. The mod will not be updated for a single dude who wants to use fabric because he is bad. Omegalul
> > > 
> > > 
> > > Are you trying to insult me? What was your goal here. Better stop using your dad's pc, 5yo.
> > 
> > 
> > He's trying to tell you how absurd it is to update a mod to the latest version for one person. Especially when the mod is ran by one person. For free. Think about what you're requesting for a moment. Also, I find it strange how you don't tell this person there isn't a fabric version for 1.8 but you tell me when I clearly state it was a hypothetical.
> 
> I'd like to hear the developer itself. I just asked, hoping for a dev reply, but you guys came and thought you knew, what he'd say. Just stop and wait for the owner.
You waited over a month. The developer has no reason want to update to 1.16, you can ask in the discord. https://discord.gg/xtQ6AZSW
Because you didn't take the time to ask in the discord, we're using our time to explain to you why the dev does not update it.

**Comment by Firewolf05** [comment]
> > > > Why would you use fabric for 1.8.9 if all mods except a few are on Forge. Although Fabric is not compatible with forge. You can say whatever you want. The mod will not be updated for a single dude who wants to use fabric because he is bad. Omegalul
> > > 
> > > 
> > > Are you trying to insult me? What was your goal here. Better stop using your dad's pc, 5yo.
> > 
> > 
> > He's trying to tell you how absurd it is to update a mod to the latest version for one person. Especially when the mod is ran by one person. For free. Think about what you're requesting for a moment. Also, I find it strange how you don't tell this person there isn't a fabric version for 1.8 but you tell me when I clearly state it was a hypothetical.
> 
> I'd like to hear the developer itself. I just asked, hoping for a dev reply, but you guys came and thought you knew, what he'd say. Just stop and wait for the owner.

arent you the one danker banned cause you where annoying about this? yeah i dont think comming here will help, as we answered you many times in discord, both me and danker, the mod wont update to other versions other than 1.8.9 since hypixel runs on 1.8.9

**Comment by UltraBlackLinux** [comment]
> > > > > Why would you use fabric for 1.8.9 if all mods except a few are on Forge. Although Fabric is not compatible with forge. You can say whatever you want. The mod will not be updated for a single dude who wants to use fabric because he is bad. Omegalul
> > > > 
> > > > 
> > > > Are you trying to insult me? What was your goal here. Better stop using your dad's pc, 5yo.
> > > 
> > > 
> > > He's trying to tell you how absurd it is to update a mod to the latest version for one person. Especially when the mod is ran by one person. For free. Think about what you're requesting for a moment. Also, I find it strange how you don't tell this person there isn't a fabric version for 1.8 but you tell me when I clearly state it was a hypothetical.
> > 
> > 
> > I'd like to hear the developer itself. I just asked, hoping for a dev reply, but you guys came and thought you knew, what he'd say. Just stop and wait for the owner.
> 
> arent you the one danker banned cause you where annoying about this? yeah i dont think comming here will help, as we answered you many times in discord, both me and danker, the mod wont update to other versions other than 1.8.9 since hypixel runs on 1.8.9

I was not being annoying. You just were assholes and version-racists.

**Comment by Firewolf05** [comment]
> I was not being annoying. You just were assholes and version-racists.

 how are we "version-racists" when hypixel is the one not updated to latest mc version and YOU are the one calling everyone retards for using 1.8.9, also yes you were being annoying you cant deny that

**Comment by TheLegendOfKitty** [comment]
> > > > > > Why would you use fabric for 1.8.9 if all mods except a few are on Forge. Although Fabric is not compatible with forge. You can say whatever you want. The mod will not be updated for a single dude who wants to use fabric because he is bad. Omegalul
> > > > > 
> > > > > 
> > > > > Are you trying to insult me? What was your goal here. Better stop using your dad's pc, 5yo.
> > > > 
> > > > 
> > > > He's trying to tell you how absurd it is to update a mod to the latest version for one person. Especially when the mod is ran by one person. For free. Think about what you're requesting for a moment. Also, I find it strange how you don't tell this person there isn't a fabric version for 1.8 but you tell me when I clearly state it was a hypothetical.
> > > 
> > > 
> > > I'd like to hear the developer itself. I just asked, hoping for a dev reply, but you guys came and thought you knew, what he'd say. Just stop and wait for the owner.
> > 
> > 
> > arent you the one danker banned cause you where annoying about this? yeah i dont think comming here will help, as we answered you many times in discord, both me and danker, the mod wont update to other versions other than 1.8.9 since hypixel runs on 1.8.9
> 
> I was not being annoying. You just were assholes and version-racists.

you're literally calling us retarded for using 1.8.9 and we are version racists??

**Comment by UltraBlackLinux** [comment]
> > I was not being annoying. You just were assholes and version-racists.
> 
> how are we "version-racists" when hypixel is the one not updated to latest mc version and YOU are the one calling everyone retards for using 1.8.9, also yes you were being annoying you cant deny that

I was calling you retards, since you guys decided to go off track, e.g. my youtube subsciptions, and staff, aka you, decided, that this was perfectly fine. I just called you, what you where, at that moment, isn't that understandable?

**Comment by UltraBlackLinux** [comment]
> > > > > > > Why would you use fabric for 1.8.9 if all mods except a few are on Forge. Although Fabric is not compatible with forge. You can say whatever you want. The mod will not be updated for a single dude who wants to use fabric because he is bad. Omegalul
> > > > > > 
> > > > > > 
> > > > > > Are you trying to insult me? What was your goal here. Better stop using your dad's pc, 5yo.
> > > > > 
> > > > > 
> > > > > He's trying to tell you how absurd it is to update a mod to the latest version for one person. Especially when the mod is ran by one person. For free. Think about what you're requesting for a moment. Also, I find it strange how you don't tell this person there isn't a fabric version for 1.8 but you tell me when I clearly state it was a hypothetical.
> > > > 
> > > > 
> > > > I'd like to hear the developer itself. I just asked, hoping for a dev reply, but you guys came and thought you knew, what he'd say. Just stop and wait for the owner.
> > > 
> > > 
> > > arent you the one danker banned cause you where annoying about this? yeah i dont think comming here will help, as we answered you many times in discord, both me and danker, the mod wont update to other versions other than 1.8.9 since hypixel runs on 1.8.9
> > 
> > 
> > I was not being annoying. You just were assholes and version-racists.
> 
> you're literally calling us retarded for using 1.8.9 and we are version racists??

Oh did I call you a retard for using 1.8.9? I don't think so.
Long answer:
__**NO**__

**Comment by Firewolf05** [comment]
> Oh did I call you a retard for using 1.8.9? I don't think so.
> Long answer:
> ****NO****

unfortunatly banning someone deletes his messages so i dont have proof of it, but yes i 100% remember that you called us retarded, i am not sure if it was for using 1.8.9 but still

**Comment by Firewolf05** [comment]
> > > I was not being annoying. You just were assholes and version-racists.
> > 
> > 
> > how are we "version-racists" when hypixel is the one not updated to latest mc version and YOU are the one calling everyone retards for using 1.8.9, also yes you were being annoying you cant deny that
> 
> I was calling you retards, since you guys decided to go off track, e.g. into my youtube subsciptions, and staff, aka you, decided, that this was perfectly fine. I just called you, what you were, at that moment, isn't that understandable?

the one searching your youtube subs was muted aswell but you were the one being an asshole

**Comment by TheLegendOfKitty** [comment]
> > > > I was not being annoying. You just were assholes and version-racists.
> > > 
> > > 
> > > how are we "version-racists" when hypixel is the one not updated to latest mc version and YOU are the one calling everyone retards for using 1.8.9, also yes you were being annoying you cant deny that
> > 
> > 
> > I was calling you retards, since you guys decided to go off track, e.g. into my youtube subsciptions, and staff, aka you, decided, that this was perfectly fine. I just called you, what you were, at that moment, isn't that understandable?
> 
> the one searching your youtube subs was muted aswell but you were the one being an asshole

I would not be surprised if he was being an asshole considering how he's speaking right now

**Comment by UltraBlackLinux** [comment]
> > Oh did I call you a retard for using 1.8.9? I don't think so.
> > Long answer:
> > ****NO****
> 
> unfortunatly banning someone deletes his messages so i dont have proof of it, but yes i 100% remember that you called us retarded, i am not sure if it was for using 1.8.9 but still
TBH you could maybe decide to read correcty and not mix stuff up so hard. 
Again: I was calling you retards since one went into my youtube subs, and whatnot, and you decided to find that perfectly fine and do nothing at all. Calling you retards was perfectly correct.

**Comment by UltraBlackLinux** [comment]
> > > > > I was not being annoying. You just were assholes and version-racists.
> > > > 
> > > > 
> > > > how are we "version-racists" when hypixel is the one not updated to latest mc version and YOU are the one calling everyone retards for using 1.8.9, also yes you were being annoying you cant deny that
> > > 
> > > 
> > > I was calling you retards, since you guys decided to go off track, e.g. into my youtube subsciptions, and staff, aka you, decided, that this was perfectly fine. I just called you, what you were, at that moment, isn't that understandable?
> > 
> > 
> > the one searching your youtube subs was muted aswell but you were the one being an asshole
> 
> I would not be surprised if he was being an asshole considering how he's speaking right now

You should consider to shut up, since you have no clue, what happened.

**Comment by UltraBlackLinux** [comment]
I am gonna close this now. I can code my own mods by now, I don't care anymore.

**Comment by TheLegendOfKitty** [comment]
> I am gonna close this now. I can code my own mods by now, I don't care anymore.

I take it you are able to now realize that you can't just copy-paste code to update to new versions? lmfao
