### ISSUE TITLE
Experimentation Table not working

### ISSUE THREAD

**Issue by RoofTopings** [bowser0000/SkyblockMod#64]
I don't know what mod its conflicting with but when I try and use the experimentation table the solvers don't work and it won't let me click after I do the first group of a puzzle.
### Mods
AutoTip
Modcore
Danker's Skyblock Mod
AutoGG
ChatTriggers
MemoryFix
NotEnoughUpdates
Patcher
SkyBlock Addons
Vanilla Enhancements
Fullscreen Windowed

**Comment by RabbitType99** [comment]
> I don't know what mod its conflicting with but when I try and use the experimentation table the solvers don't work and it won't let me click after I do the first group of a puzzle.
> ### Mods
> AutoTip
> Modcore
> Danker's Skyblock Mod
> AutoGG
> ChatTriggers
> MemoryFix
> NotEnoughUpdates
> Patcher
> SkyBlock Addons
> Vanilla Enhancements
> Fullscreen Windowed
> 

Delete Modcore and all Fullscreen Windowed it is.included in Patcher. Although you should have a decent amount of fps. If you can click press Strg or Shift (I don't know which one) to click.

**Comment by bowser0000** [comment]
Closed due to inactivity.
