### ISSUE TITLE
Cant use /dsm ingame

### ISSUE THREAD

**Issue by AnderDQD** [bowser0000/SkyblockMod#67]
Whenever I try to type in /dsm it says unknown command

I have no there mods installed and I'm on 1.8.9

**Comment by leftclick2win** [comment]
Same!

**Comment by leftclick2win** [comment]
i realized i had the 1.5.5 version idk how i got it but i downloaded the 1.8.4 version now it works, hope this helps!

**Comment by Sychic** [comment]
> 
> 
> Whenever I try to type in /dsm it says unknown command
> 
> I have no there mods installed and I'm on 1.8.9

What version are you using?

**Comment by bowser0000** [comment]
Closed due to inactivity.
