### ISSUE TITLE
Trivia Solver

### ISSUE THREAD

**Issue by oofsamy** [bowser0000/SkyblockMod#70]
New minion added. There are now 53 unique minions and the trivia solver gets broken when it comes up with that question.

**Comment by My-Name-Is-Jeff** [comment]
Fixed in #62

**Comment by bowser0000** [comment]
Fixed in commit [21bd825](https://github.com/bowser0000/SkyblockMod/commit/21bd825c0eb2e9de970fc8b879b6901798aac52e)
