### ISSUE TITLE
Blaze puzzle solver just working wrong.

### ISSUE THREAD

**Issue by Xbfo** [bowser0000/SkyblockMod#74]
i had 3 parties kick me for ruining s+ because my solver is trash.

**Comment by My-Name-Is-Jeff** [comment]
Solver works fine. Make sure to note the room variant.

**Comment by Xbfo** [comment]
blaze solver, just wrong.

**Comment by Ldude162** [comment]
Works for me. Are you sure you're using it right?

**Comment by bennyisverycool** [comment]
if the chest is on the bottom kill the lowest health ones to the highest health, and vice versa

**Comment by bowser0000** [comment]
Closed due to inactivity
