### ISSUE TITLE
wrong box size ArachneESP, SlayerESP

### ISSUE THREAD

**Issue by CuzImClicks** [bowser0000/SkyblockMod#86]
Could you change the size of the spiders hitbox in line 80 in ArachneESP:
`AxisAlignedBB aabb = new AxisAlignedBB(arachne.posX - 0.5, arachne.posY - 1, arachne.posZ - 0.5, arachne.posX + 0.5, arachne.posY, arachne.posZ + 0.5);` to
`AxisAlignedBB aabb = new AxisAlignedBB(arachne.posX - 0.75, arachne.posY - 1, arachne.posZ - 0.75, arachne.posX + 0.75, arachne.posY, arachne.posZ + 0.75);`
and in SlayerESP line 109:
`AxisAlignedBB aabb = new AxisAlignedBB(spider.posX - 0.5, spider.posY - 1, spider.posZ - 0.5, spider.posX + 0.5, spider.posY, spider.posZ + 0.5);` to 
`AxisAlignedBB aabb = new AxisAlignedBB(spider.posX - 0.75, spider.posY - 1, spider.posZ - 0.75, spider.posX + 0.75, spider.posY, spider.posZ + 0.75);`
sorry, defenitly my mistake

**Comment by bowser0000** [comment]
Fixed in commit [a288554](https://github.com/bowser0000/SkyblockMod/commit/a288554be92f2f4ff8cdc26cd1d86d4316d7b756)
