### ISSUE TITLE
New Mod Conditions.

### ISSUE THREAD

**Issue by CPT-Blob** [bowser0000/SkyblockMod#87]
Hi there! Not necessarily an issue, but wondering if you will be updating your mod to the new mod conditions, or if I will have to switch to a different mod.

**Comment by satyamedh** [comment]
Obviously he will @CPT-Blob

**Comment by bowser0000** [comment]
Fixed in commit [df1f83c](https://github.com/bowser0000/SkyblockMod/commit/df1f83cf4ddb80969d2086cf1d7a86df9dc90653)
