### ISSUE TITLE
Regarding new features

### ISSUE THREAD

**Issue by Thrasilias** [bowser0000/SkyblockMod#92]
Ghost tracker and display isn't allowed to use and will get you most likely auto banned. should remove this asap

**Comment by bowser0000** [comment]
Why is a loot tracker bannable?

**Comment by Thrasilias** [comment]
if it's a loot tracker then u should call it diffrently then Ghost Tracker, bc when u think about it u will think u will be able to see the ghosts

**Comment by SenkiDaKitty** [comment]
> if it's a loot tracker then u should call it diffrently then Ghost Tracker, bc when u think about it u will think u will be able to see the ghosts

![image](https://user-images.githubusercontent.com/44231818/114246929-38acf280-9994-11eb-8bd1-f5f9ac87ab7d.png)
What do you think Floor trackers are for ? to see them ?
