### ISSUE TITLE
CustomMusic issues

### ISSUE THREAD

**Issue by Arti-Dev** [bowser0000/SkyblockMod#93]
The new custom music feature is pretty cool, though I ran into some issues

-Blood room music does not end when you clear it, only when you enter the boss room (may or may not have been intentional)
-Boss room music sometimes does not play when entering boss room (inconclusive, will test more later)
-DSM does not completely filter out all of the music sounds that Hypixel sends when custom music is enabled
(I really like what you did with `if (cancelNotes && event.name.startsWith("note."))`!)
(However, it also seems to cancel all of the sounds during Necron's third phase which makes me a bit sad)
(If I were to cheese it I would use the /playsound command and hide the message but that's probably not a good idea)

Quick video:
https://www.youtube.com/watch?v=mphOGhC-9e8
(Yes, Bad Apple is my blood room theme)

**Comment by SenkiDaKitty** [comment]
Can confirm the above reports ^^

**Comment by camcielinski** [comment]
I can also confirm all of the above ^
> (However, it also seems to cancel all of the sounds during Necron's third phase which makes me a bit sad)
To add onto this, it also cancels out a few other sounds:
- Dungeon buff sound
- Wither door opening
- Ice floor puzzle "completion" sound

**Comment by camcielinski** [comment]
Upon further testing, I've found out that:

- Boss music only works once per Minecraft instance - restarting Minecraft will let it work for 1 run, and every subsequent run will not have the custom boss music (until Minecraft is restarted). This seems to be well known on the Discord, but I'll add it here.
- On top of the above sounds, the following also do not play: pet level-up, rare drops, dungeon buff chest secret opening noise
- During boss fights, the "exp orb" noises are not canceled with the note block noises.
