### ISSUE TITLE
Lastest version troubles

### ISSUE THREAD

**Issue by AndrewGiusty** [bowser0000/SkyblockMod#94]
With Superpair it became blue and not green, so i tried to click it (since there was no green) and lost; 
With the Ultrasequencer it happened the same bug as old version, it picked the block and made me lost swapping it with the other one
And last (this never happened to me before) when i ended the Superpair it happened this:
The click goes negative, no matter where i click, also the timer is stuck at 1s
![2021-04-22_06 43 04](https://user-images.githubusercontent.com/53437176/115657751-b92a0680-a337-11eb-94f2-298b83c9b58c.png)
This is me clicking
![2021-04-22_06 55 36](https://user-images.githubusercontent.com/53437176/115657805-cf37c700-a337-11eb-8316-0e655c3f2db4.png)
![2021-04-22_06 55 38](https://user-images.githubusercontent.com/53437176/115657809-d068f400-a337-11eb-8c21-83536a6ca7bf.png)
![2021-04-22_06 55 47](https://user-images.githubusercontent.com/53437176/115657811-d1018a80-a337-11eb-954b-3f125875fbbd.png)
Then i pressed esc and it fixed, but i just wanted to report it since a bug can be defined an issue
Anyway i'd like there will be the thing that blocks you from clicking other stuff (like old versions), thanks for reading

**Comment by SkyBlockDev** [comment]
Blocking wrong clicks prob won't be added back since It cancels packets

**Comment by bowser0000** [comment]
Outdated.
